# Generated by Django 5.0.2 on 2024-02-22 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='pet_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pets.petmodel'),
        ),
    ]
