# Generated by Django 5.0.2 on 2024-02-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_owner_id_petmodel_owner'),
        ('portal', '0002_listings_pet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='status',
            new_name='is_found',
        ),
        migrations.AlterField(
            model_name='listings',
            name='pet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.petmodel'),
        ),
    ]
