# Generated by Django 5.0.2 on 2024-03-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_listingcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='is_found',
        ),
    ]
