# Generated by Django 5.0.2 on 2024-04-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_listingcomments_last_seen_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcomments',
            name='listing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.listings'),
        ),
    ]
