# Generated by Django 5.0.2 on 2024-02-16 20:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos'))),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('pet_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_type', models.CharField(blank=True, max_length=30, null=True)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_color', models.CharField(blank=True, max_length=40, null=True)),
                ('pet_description', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
