# Generated by Django 5.0.2 on 2024-02-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='status',
            new_name='is_active',
        ),
    ]
