# Generated by Django 5.0.2 on 2024-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
