# Generated by Django 5.0.2 on 2024-02-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usermodel_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pet_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
