# Generated by Django 5.0.2 on 2024-02-25 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_reviews_rating_reviews_reviews_ratings_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
