# Generated by Django 5.0.2 on 2024-02-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_reviews_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pet_color',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pet_description',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pet_picture',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pet_type',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
