# Generated by Django 5.0.2 on 2024-03-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_usermodel_breed_remove_usermodel_pet_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='ReviewsModel',
        ),
    ]
