# Generated by Django 5.0.2 on 2024-02-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petmodel',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
