# Generated by Django 5.0.2 on 2024-02-25 22:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_owner_id_petmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='pet_profile',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/images')),
        ),
    ]
