# Generated by Django 5.0.2 on 2024-02-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_petmodel_pet_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='pet_profile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
